#%RAML 1.0 Trait


responses:
      400:
        body:
          application/json:
            example:
              {
                "message": "Bad request"
              }
      500:
        body:
          application/json:
            example:
              {
                "message": "internal server error"
              }